application: techaguru-orangepineapple
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

- url: /static/js
  static_dir: ../static/js

- url: /static/css
  static_dir: ../static/css

